services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
