FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y gcc

COPY api/requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY api /app/

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]