# Generated by Django 6.0 on 2025-12-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do produto', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço do produto', max_digits=10)),
                ('in_stock', models.BooleanField(default=True, help_text='O produto está disponível em estoque?')),
            ],
        ),
    ]
