# Generated by Django 5.2.8

from django.db import migrations


def create_initial_categories(apps, schema_editor):
    """
    Cria as categorias iniciais no banco de dados.
    """
    Category = apps.get_model('products', 'Category')
    categories_to_create = [
        'Eletrônicos e informática',
        'Moda e acessórios',
        'Casa e decoração',
    ]

    for category_name in categories_to_create:
        # Usamos get_or_create para evitar duplicatas se a migração for executada mais de uma vez
        Category.objects.get_or_create(name=category_name)


def remove_initial_categories(apps, schema_editor):
    """
    Remove as categorias iniciais (operação reversa para o caso de 'unmigrate').
    """
    Category = apps.get_model('products', 'Category')
    category_names_to_delete = ['Eletrônicos e informática', 'Moda e acessórios', 'Casa e decoração']
    Category.objects.filter(name__in=category_names_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),  # Certifique-se que este é o nome da sua migração anterior
    ]

    operations = [
        migrations.RunPython(create_initial_categories, reverse_code=remove_initial_categories),
    ]
