# Generated by Django 6.0 on 2025-12-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_initial_categories'),
        ('products', '0002_category_product_category'),
    ]

    operations = [
    ]
